### ISSUE TITLE
Adding a non open source project ? (TextSynth Server)

### ISSUE THREAD

**Issue by Hugi-R** [imaurer/awesome-decentralized-llm#7]
In my search for easy LLM inference on PC, I stumbled on [TextSynth Server](https://bellard.org/ts_server/), distributed as shareware for CPU inference. It provides easy inference with a webgui on Linux and Windows, supporting a bunch of models, some of them quantized.

So far, it's the easiest way I found to run an LLM locally, but since it's not open source, I don't know if it can be added.

**Comment by imaurer** [comment]
Yes I will add it because it is Fabrice Bellard.

Let me think a bit on whether I need a new section or notation.

**Comment by imaurer** [comment]
Added and thanks!
